import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JFileChooser;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class MainUI extends javax.swing.JFrame implements ActionListener {
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        initListener();
        initCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        historyPanel = new javax.swing.JPanel();
        hisComboBox = new javax.swing.JComboBox();
        his_Button = new javax.swing.JButton();
        hisPanel1 = new javax.swing.JPanel();
        testPanel = new ChartPanel(null);
        timeComboBox0 = new javax.swing.JComboBox();
        timeComboBox1 = new javax.swing.JComboBox();
        toLabel = new javax.swing.JLabel();
        timeComboBox2 = new javax.swing.JComboBox();
        timeComboBox3 = new javax.swing.JComboBox();
        lightPointPanel = new javax.swing.JPanel();
        lightPoint0 = new javax.swing.JPanel();
        lightPoint1 = new javax.swing.JPanel();
        lightPoint2 = new javax.swing.JPanel();
        lightPoint3 = new javax.swing.JPanel();
        lightPoint4 = new javax.swing.JPanel();
        lightPoint5 = new javax.swing.JPanel();
        distencePanel = new javax.swing.JPanel();
        disLabel = new javax.swing.JLabel();
        disTextField = new javax.swing.JTextField();
        disComboBox = new javax.swing.JComboBox();
        disButton = new javax.swing.JButton();
        jPanel2 = new ChartPanel(null);
        recommendationPanel = new javax.swing.JPanel();
        recomComboBox = new javax.swing.JComboBox();
        recomButton = new javax.swing.JButton();
        recomLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        accountLabel = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        docMenu = new javax.swing.JMenu();
        docMenuItem0 = new javax.swing.JMenuItem();
        docMenuItem1 = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        accMenuItem0 = new javax.swing.JMenuItem();
        sysMenu = new javax.swing.JMenu();
        sysMenuItem0 = new javax.swing.JMenuItem();
        sysMenuItem1 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setToolTipText("");
        TabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        hisComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "按分类", "按时间", "按时间区间" }));

        his_Button.setText("查询");
        his_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                his_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout hisPanel1Layout = new javax.swing.GroupLayout(hisPanel1);
        hisPanel1.setLayout(hisPanel1Layout);
        hisPanel1Layout.setHorizontalGroup(
            hisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hisPanel1Layout.setVerticalGroup(
            hisPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        timeComboBox0.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));

        timeComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        toLabel.setFont(new java.awt.Font("黑体", 0, 14)); // NOI18N
        toLabel.setText("至");

        timeComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));

        timeComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addComponent(hisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timeComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(his_Button)
                        .addContainerGap(223, Short.MAX_VALUE))))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toLabel)
                    .addComponent(timeComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(his_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hisPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("我的历史", historyPanel);

        javax.swing.GroupLayout lightPoint0Layout = new javax.swing.GroupLayout(lightPoint0);
        lightPoint0.setLayout(lightPoint0Layout);
        lightPoint0Layout.setHorizontalGroup(
            lightPoint0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lightPoint0Layout.setVerticalGroup(
            lightPoint0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPoint1Layout = new javax.swing.GroupLayout(lightPoint1);
        lightPoint1.setLayout(lightPoint1Layout);
        lightPoint1Layout.setHorizontalGroup(
            lightPoint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        lightPoint1Layout.setVerticalGroup(
            lightPoint1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPoint2Layout = new javax.swing.GroupLayout(lightPoint2);
        lightPoint2.setLayout(lightPoint2Layout);
        lightPoint2Layout.setHorizontalGroup(
            lightPoint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        lightPoint2Layout.setVerticalGroup(
            lightPoint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPoint3Layout = new javax.swing.GroupLayout(lightPoint3);
        lightPoint3.setLayout(lightPoint3Layout);
        lightPoint3Layout.setHorizontalGroup(
            lightPoint3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        lightPoint3Layout.setVerticalGroup(
            lightPoint3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPoint4Layout = new javax.swing.GroupLayout(lightPoint4);
        lightPoint4.setLayout(lightPoint4Layout);
        lightPoint4Layout.setHorizontalGroup(
            lightPoint4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lightPoint4Layout.setVerticalGroup(
            lightPoint4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPoint5Layout = new javax.swing.GroupLayout(lightPoint5);
        lightPoint5.setLayout(lightPoint5Layout);
        lightPoint5Layout.setHorizontalGroup(
            lightPoint5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lightPoint5Layout.setVerticalGroup(
            lightPoint5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lightPointPanelLayout = new javax.swing.GroupLayout(lightPointPanel);
        lightPointPanel.setLayout(lightPointPanelLayout);
        lightPointPanelLayout.setHorizontalGroup(
            lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightPointPanelLayout.createSequentialGroup()
                .addGroup(lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lightPoint3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lightPoint1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightPoint2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        lightPointPanelLayout.setVerticalGroup(
            lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightPointPanelLayout.createSequentialGroup()
                .addGroup(lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lightPoint0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lightPointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightPoint3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lightPoint5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TabbedPane.addTab("我的亮点", lightPointPanel);

        disLabel.setText("对比账号：");

        disTextField.setText("对比账号");

        disComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "按分类", "按时间" }));

        disButton.setText("查询");
        disButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout distencePanelLayout = new javax.swing.GroupLayout(distencePanel);
        distencePanel.setLayout(distencePanelLayout);
        distencePanelLayout.setHorizontalGroup(
            distencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(distencePanelLayout.createSequentialGroup()
                        .addComponent(disLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(disComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disButton)
                        .addContainerGap(359, Short.MAX_VALUE))))
        );
        distencePanelLayout.setVerticalGroup(
            distencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distencePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disLabel)
                    .addComponent(disTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPane.addTab("差距对比", distencePanel);

        recomComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "默认推荐", "动态规划", "贪心", "数据结构", "图论" }));

        recomButton.setText("查询");

        javax.swing.GroupLayout recommendationPanelLayout = new javax.swing.GroupLayout(recommendationPanel);
        recommendationPanel.setLayout(recommendationPanelLayout);
        recommendationPanelLayout.setHorizontalGroup(
            recommendationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recommendationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recommendationPanelLayout.createSequentialGroup()
                        .addComponent(recomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recomButton))
                    .addComponent(recomLabel))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        recommendationPanelLayout.setVerticalGroup(
            recommendationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recommendationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recommendationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recomButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recomLabel)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        TabbedPane.addTab("荐题系统", recommendationPanel);

        accountLabel.setText("当前账号：");

        account.setText("null");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(account)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountLabel)
                    .addComponent(account))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        docMenu.setBorder(null);
        docMenu.setText("文件");
        docMenu.setToolTipText("");

        docMenuItem0.setText("导出文件");
        docMenuItem0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docMenuItem0ActionPerformed(evt);
            }
        });
        docMenu.add(docMenuItem0);

        docMenuItem1.setText("导入分类");
        docMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //docMenuItem0ActionPerformed(evt);
            	JFileChooser fd = new JFileChooser();
            	//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            	fd.showOpenDialog(null);
            	File sourceFile = fd.getSelectedFile();
            	String sort = "E:\\doc\\sort.txt";
            	File targetFile = new File(sort);
            	
            	if(sourceFile != null){
            		FileInputStream fi = null;
                    FileOutputStream fo = null;
                    FileChannel in = null;
                    FileChannel out = null;
                    try {
                        fi = new FileInputStream(sourceFile);
                        fo = new FileOutputStream(targetFile);
                        in = fi.getChannel();//得到对应的文件通道
                        out = fo.getChannel();//得到对应的文件通道
                        in.transferTo(0, in.size(), out);//连接两个通道，并且从in通道读取，然后写入out通道
                    } catch (IOException e) {
                        e.printStackTrace();
                    } finally {
                        try {
                            fi.close();
                            in.close();
                            fo.close();
                            out.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
            	}
            }
        });
        docMenu.add(docMenuItem1);

        MenuBar.add(docMenu);

        accountMenu.setText("账号");

        accMenuItem0.setText("切换帐号");
        accountMenu.add(accMenuItem0);

        MenuBar.add(accountMenu);

        sysMenu.setBorder(null);
        sysMenu.setText("系统");

        sysMenuItem0.setText("更新软件");
        sysMenu.add(sysMenuItem0);

        sysMenuItem1.setText("联系我们");
        sysMenu.add(sysMenuItem1);

        MenuBar.add(sysMenu);

        helpMenu.setText("帮助");
        MenuBar.add(helpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 489, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    private void his_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void disButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void docMenuItem0ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainUI.class.getName()). log(Level.SEVERE, null, ex);
                }
                MainUI godUI = new MainUI();
                godUI.setLocationRelativeTo(null); //窗口居中
                godUI.setVisible(true);
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
                godUI.firstLogin();
                //System.out.println("11111");
                godUI.initData();
                godUI.loadChart();
                //System.out.println("22222");
                /*
                Map<String,Integer> k = godUI.countType();
                Iterator<String> iterator = typemap.keySet().iterator();
                while(iterator.hasNext()) {
                     String ss = iterator.next();
                     System.out.println(ss+" "+k.get(ss));
                }
                  */      
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JMenuItem accMenuItem0;
    private javax.swing.JLabel account;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JButton disButton;
    private javax.swing.JComboBox disComboBox;
    private javax.swing.JLabel disLabel;
    private javax.swing.JTextField disTextField;
    private javax.swing.JPanel distencePanel;
    private javax.swing.JMenu docMenu;
    private javax.swing.JMenuItem docMenuItem0;
    private javax.swing.JMenuItem docMenuItem1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JComboBox hisComboBox;
    private javax.swing.JPanel hisPanel1;
    private javax.swing.JButton his_Button;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JPanel jPanel1;
    private ChartPanel jPanel2;
    private javax.swing.JPanel lightPoint0;
    private javax.swing.JPanel lightPoint1;
    private javax.swing.JPanel lightPoint2;
    private javax.swing.JPanel lightPoint3;
    private javax.swing.JPanel lightPoint4;
    private javax.swing.JPanel lightPoint5;
    private javax.swing.JPanel lightPointPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton recomButton;
    private javax.swing.JComboBox recomComboBox;
    private javax.swing.JPanel recommendationPanel;
    private javax.swing.JLabel recomLabel;
    private javax.swing.JMenu sysMenu;
    private javax.swing.JMenuItem sysMenuItem0;
    private javax.swing.JMenuItem sysMenuItem1;
    private ChartPanel testPanel;
    private javax.swing.JComboBox timeComboBox0;
    private javax.swing.JComboBox timeComboBox1;
    private javax.swing.JComboBox timeComboBox2;
    private javax.swing.JComboBox timeComboBox3;
    private javax.swing.JLabel toLabel;
 // End of variables declaration   
    
    private String user_name; //当前用户account
    private String cmp_name; //对比账号account
    private Map<String,Integer> timemap; //按时间的统计
    private Map<String,Integer> typemap; //按分类的统计
    private Map<String,Integer> cmp_timemap; //对比对象按时间的统计
    private Map<String,Integer> cmp_typemap; //对比对象按分类的统计
    private String timekey[] = new String[1000]; //按时间先后排序
    private String cmp_timekey[] = new String[1000]; //按时间先后排序
    private int num, cmp_num; // 排序后数组元素的个数
    private String t0, t1, t2, t3; //按时间区间页，默认时间
    private Map<String,Integer> cmpmap = new HashMap<String,Integer>(); //记录对比对象
    private ArrayList<String> titleArray = new ArrayList<String>();
    private String recomType;
    
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==hisComboBox)
        {
            int index = hisComboBox.getSelectedIndex();
            if(index==2)
            {
                timeComboBox0.setVisible(true);
                timeComboBox1.setVisible(true);
                timeComboBox2.setVisible(true);
                timeComboBox3.setVisible(true);
                toLabel.setVisible(true);
                his_Button.setVisible(true);
                
            }
            if(index==0)
            {
                timeComboBox0.setVisible(false);
                timeComboBox1.setVisible(false);
                timeComboBox2.setVisible(false);
                timeComboBox3.setVisible(false);
                toLabel.setVisible(false);
                his_Button.setVisible(false);
                testPanel.setChart(typeCreateChart(typeCreateDataset()));
            }
            if(index==1)
            {
                timeComboBox0.setVisible(false);
                timeComboBox1.setVisible(false);
                timeComboBox2.setVisible(false);
                timeComboBox3.setVisible(false);
                toLabel.setVisible(false);
                his_Button.setVisible(false);
                testPanel.setChart(timeCreateChart(timeCreateDataset()));
            }
        }
        if(e.getSource()==accMenuItem0)
        {
       	 firstLogin();
            //System.out.println("11111");
            initData();
            loadChart();
        }
        if(e.getSource()==timeComboBox0)
        {
       	 t0 = (String) timeComboBox0.getSelectedItem();
        }
        if(e.getSource()==timeComboBox1)
        {
       	 t1 = (String) timeComboBox1.getSelectedItem();
        }
        if(e.getSource()==timeComboBox2)
        {
       	 t2 = (String) timeComboBox2.getSelectedItem();
        }
        if(e.getSource()==timeComboBox3)
        {
       	 t3 = (String) timeComboBox3.getSelectedItem();
        }
        if(e.getSource()==his_Button) 
        {
       	 testPanel.setChart(timeCreateChart(timeCreateDataset2()));
        }
        if(e.getSource()==disButton)
        {
        	cmp_name = disTextField.getText();
        	//System.out.println(cmp_name);
        	//System.out.println(cmpmap.containsKey(cmp_name));
        	if(!cmpmap.containsKey(cmp_name)) {
        		InfoDownload cmp = new InfoDownload();
        		if(cmp.init(cmp_name)) {
        			cmpmap.put(cmp_name, 1);
        			cmp.getinfo();
        		}
        		else {
        			JOptionPane.showMessageDialog(null, "账号不存在");
        		}
        	}
        	if(cmpmap.containsKey(cmp_name)) {
        		DataCount cmp_dc = new DataCount();
        		cmp_dc.init(cmp_name);
        		cmp_timemap = cmp_dc.getdata();
    			cmp_typemap = cmp_dc.countType();
    			sort_cmp_time();
    			int index = disComboBox.getSelectedIndex();
    			if(index==0) {
    				jPanel2.setChart(typeCreateChart(typeCreateDataset2()));
    			}
    			else if(index==1) {
    				jPanel2.setChart(timeCreateChart(timeCreateDataset3()));
    			}
        	}
        		
        }
        if(e.getSource()==recomComboBox) {
        	recomType = recomComboBox.getSelectedItem().toString();
        }
        if(e.getSource()==recomButton) {
        	showRecomTitle(recomType);
        }
   }

   private void initListener() {
       his_Button.addActionListener(this);
       disButton.addActionListener(this);
       recomButton.addActionListener(this);
       hisComboBox.addActionListener(this);
       accMenuItem0.addActionListener(this);
       timeComboBox0.addActionListener(this);
       timeComboBox1.addActionListener(this);
       timeComboBox2.addActionListener(this);
       timeComboBox3.addActionListener(this);
       recomButton.addActionListener(this);
       recomComboBox.addActionListener(this);
   }
   
   private CategoryDataset typeCreateDataset2() {
       
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       Iterator<String> itertype = typemap.keySet().iterator();
       while(itertype.hasNext()) {
            String ss = itertype.next();
            dataset.setValue(typemap.get(ss),user_name,ss);
       }
       Iterator<String> itercmptype = cmp_typemap.keySet().iterator();
       while(itercmptype.hasNext()) {
            String ss = itercmptype.next();
            dataset.setValue(cmp_typemap.get(ss),cmp_name,ss);
       }
       return dataset;
   }
   
private CategoryDataset typeCreateDataset() {
       
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       Iterator<String> itertype = typemap.keySet().iterator();
       int index = 0;
       while(itertype.hasNext()) {
            String ss = itertype.next();
            dataset.setValue(typemap.get(ss),user_name,ss);
            index++;
       }
       return dataset;
   }

   private  JFreeChart typeCreateChart(CategoryDataset dataset) //用数据集创建一个图表
   {
   	JFreeChart chart=ChartFactory.createBarChart("hi", "类别", 
               "题数", dataset, PlotOrientation.VERTICAL, true, true, false); //创建一个JFreeChart
       chart.setTitle(new TextTitle("按分类题数",new Font("宋体",Font.BOLD+Font.ITALIC,20)));//可以重新设置标题，替换“hi”标题
       //chart.getRenderingHints().put(RenderingHints.KEY_TEXT_ANTIALIASING,RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);
       CategoryPlot plot=(CategoryPlot)chart.getPlot();//获得图标中间部分，即plot
       CategoryAxis categoryAxis=plot.getDomainAxis();//获得横坐标
       categoryAxis.setLabelFont(new Font("黑体",Font.BOLD,16));//设置横坐标字体
       //设置横坐标Label倾斜角度
       categoryAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
       BarRenderer render = (BarRenderer) plot.getRenderer();
       render.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator());//显示每个柱的数值 
       render.setBaseItemLabelsVisible(true); 
       //设置每组柱子间的间隔
       //render.setItemMargin(0.0);
      // plot.setBackgroundPaint(Color.lightGray);

       
       return chart;
   }
   
   private  CategoryDataset timeCreateDataset3() //创建柱状图数据集
   {	
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       for(int i=0; i<num; i++) {
       	dataset.setValue(timemap.get(timekey[i]),user_name,timekey[i]);
       }
       for(int i=0; i<cmp_num; i++) {
          	dataset.setValue(cmp_timemap.get(cmp_timekey[i]),cmp_name,cmp_timekey[i]);
          }
       return dataset;
   }
   
   private  CategoryDataset timeCreateDataset2()
   {
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       //System.out.println(t0+t1+t2+t3);
       int a0 = Integer.parseInt(t0);
       int a1 = Integer.parseInt(t1);
       int a2 = Integer.parseInt(t2);
       int a3 = Integer.parseInt(t3);
       int index = 0;
       for(int i=a0; i<=a2; i++)
       {
       	int l=1, r=12;
       	if(i==a0) l = a1;
       	if(i==a2) r = a3;
       	for(int j=l; j<=r; j++)
       	{
       		String ss = "";
       		ss = ss + String.valueOf(i);
       		if(j<10) ss = ss + "0" + String.valueOf(j);
       		else ss = ss + String.valueOf(j);
       		if(timemap.containsKey(ss)) {
       			dataset.setValue(timemap.get(ss), user_name, ss);
       			index++;
       		}
       	}
       }
       return dataset;
   }
   
   private  CategoryDataset timeCreateDataset() //创建柱状图数据集
   {	
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       for(int i=0; i<num; i++) {
       	dataset.setValue(timemap.get(timekey[i]),user_name,timekey[i]);
       }
       return dataset;
   }
   
   private  JFreeChart timeCreateChart(CategoryDataset dataset) //用数据集创建一个图表
   {
   	JFreeChart chart = ChartFactory.createLineChart(
               "按时间题数",   // chart title
               null,                       // domain axis label
               "题数",                   // range axis label
               dataset,                         // data
               PlotOrientation.VERTICAL,        // orientation
               true,                           // include legend
               true,                            // tooltips
               false                            // urls
           );
   	
           //chart.setBackgroundPaint(Color.white);

           CategoryPlot plot = (CategoryPlot) chart.getPlot();
           
           //plot.setBackgroundPaint(Color.lightGray);
           
           plot.setRangeGridlinesVisible(false);
           // customise the range axis...
           NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
           rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

           // customise the renderer...
           LineAndShapeRenderer renderer 
                   = (LineAndShapeRenderer) plot.getRenderer();
           renderer.setBaseShapesVisible(true);
           renderer.setDrawOutlines(true);
           renderer.setUseFillPaint(true);
           renderer.setBaseFillPaint(Color.white);
           renderer.setSeriesStroke(0, new BasicStroke(3.0f));
           renderer.setSeriesOutlineStroke(0, new BasicStroke(2.0f));
           renderer.setSeriesShape(0, new Ellipse2D.Double(-5.0, -5.0, 10.0, 10.0));
           CategoryAxis categoryAxis=plot.getDomainAxis();//获得横坐标
         //设置横坐标Label倾斜角度
           categoryAxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
           renderer.setBaseItemLabelGenerator(new StandardCategoryItemLabelGenerator());//显示每个柱的数值 
           renderer.setBaseItemLabelsVisible(true); 
           return chart;
   }
   
   private void showRecomTitle(String type) {
	   titleArray = TypeTitle.getTypeTitle(recomType);
	   String text = "<html>" + type + ":<br \\><br \\>";
	   int index = 0;
	   for(String tmp:titleArray) {
		   text = text + tmp + "   ";
		   index++;
		   if(index%7==0)
			   text = text + "<br \\><br \\>";
	   }
	   text = text + "<html\\>";
	   recomLabel.setText(text);
	   
   }
   
   private void firstLogin() {
       boolean flag = true;
       String tip = "请输入账号";
       while(flag) {
           user_name = JOptionPane.showInputDialog(null, tip, "", WIDTH);
           
           InfoDownload info_obj = new InfoDownload();
           if(info_obj.init(user_name)) {
               info_obj.getinfo();
               account.setText(user_name);
               flag = false;
           }
           else {
               tip = "账号不存在，请重新输入";
           }
                   
           /*
           account.setText(user_name);
           flag = false;
       */
       }
   }


   //获取分类的题数

  private void loadChart() {
   	testPanel.setChart(typeCreateChart(typeCreateDataset()));
   	//testPanel.setPreferredSize(new Dimension(1000,400));
   }
   
 private void initData() {
       
       //System.out.println("33333333");
       DataCount dc = new DataCount();
       dc.init(user_name);
       timemap = dc.getdata();
       //排序
       num = 0;
       Iterator<String> iter = timemap.keySet().iterator();
       while(iter.hasNext()) {
           //System.out.println("44444444");
            String ss = iter.next();
            //System.out.println(ss);
            timekey[num] = ss;
            num++;
       }
       //冒泡
       for(int i=0; i<num-1; i++)
       {
       	for(int j=0; j<num-i-1; j++)
       	{
       		int j0 = Integer.parseInt(timekey[j]);
       		int j1 = Integer.parseInt(timekey[j+1]);
       		if(j0 > j1)
       		{
       			String tmp;
       			tmp = timekey[j]; timekey[j] = timekey[j+1]; timekey[j+1] = tmp;
       		}
       	}
       }
       for(int i=0; i<num; i++) {
       	System.out.println(timekey[i]);
       }
       
       Iterator<String> itertime = timemap.keySet().iterator();
       while(itertime.hasNext()) {
            String ss = itertime.next();
            System.out.println(ss+" "+timemap.get(ss));
       }
       typemap = dc.countType();
       Iterator<String> itertype = typemap.keySet().iterator();
       while(itertype.hasNext()) {
           //System.out.println("44444444");
            String ss = itertype.next();
            System.out.println(ss+" "+typemap.get(ss));
       }
       
   }
   
   private void sort_cmp_time() {
	   cmp_num = 0;
       Iterator<String> iter = cmp_timemap.keySet().iterator();
       while(iter.hasNext()) {
           //System.out.println("44444444");
            String ss = iter.next();
            //System.out.println(ss);
            cmp_timekey[cmp_num] = ss;
            cmp_num++;
       }
       //冒泡
       for(int i=0; i<cmp_num-1; i++)
       {
       	for(int j=0; j<cmp_num-i-1; j++)
       	{
       		int j0 = Integer.parseInt(cmp_timekey[j]);
       		int j1 = Integer.parseInt(cmp_timekey[j+1]);
       		if(j0 > j1)
       		{
       			String tmp;
       			tmp = cmp_timekey[j]; cmp_timekey[j] = cmp_timekey[j+1]; cmp_timekey[j+1] = tmp;
       		}
       	}
       }
   }
   
   private void initCombobox() {
      timeComboBox0.setVisible(false);
      timeComboBox1.setVisible(false);
      timeComboBox2.setVisible(false);
      timeComboBox3.setVisible(false);
      toLabel.setVisible(false);
      his_Button.setVisible(false);
      t0 = "2004";
      t1 = "01";
      t2 = "2004";
      t3 = "01";
   }
}